// frontend-angular/src/app/components/faq-section/faq-section.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-faq-section',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section id="faq" style="padding: 4rem 1.5rem; background-color: #0d0d0d;">
      <div style="max-width: 900px; margin: 0 auto;">
        <div class="rooms-header" style="text-align: center; margin-bottom: 3rem;">
          <p class="sec-label">Preguntas frecuentes</p>
          <h2 class="sec-title">Resuelve tus dudas antes de viajar</h2>
        </div>

        <div style="display: flex; flex-direction: column; gap: 1rem;">
          <div
            *ngFor="let faq of faqs; let idx = index"
            style="background: rgba(255, 255, 255, 0.02); border: 1px solid rgba(212, 175, 55, 0.2); border-radius: 8px; overflow: hidden;"
          >
            <button
              type="button"
              (click)="toggle(idx)"
              style="width: 100%; padding: 1.25rem 1.5rem; display: flex; justify-content: space-between; align-items: center; background: none; border: none; color: #ffffff; font-size: 1.05rem; font-weight: 600; cursor: pointer; text-align: left;"
            >
              <span>{{ faq.q }}</span>
              <span style="color: var(--gold); font-size: 1.3rem; margin-left: 1rem;">
                {{ openIdx === idx ? '−' : '+' }}
              </span>
            </button>
            <div
              *ngIf="openIdx === idx"
              style="padding: 0 1.5rem 1.25rem 1.5rem; color: #cccccc; line-height: 1.6; border-top: 1px solid rgba(255, 255, 255, 0.05);"
            >
              <p style="margin: 0;">{{ faq.a }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  `
})
export class FaqSectionComponent {
  openIdx: number | null = 0;

  faqs = [
    {
      q: '¿Cuáles son los horarios de Check-in y Check-out?',
      a: 'El Check-in está disponible a partir de las 15:00 hrs y el Check-out se realiza hasta las 12:00 hrs del mediodía. Contamos con servicio de custodia de equipaje y late check-out bajo disponibilidad.'
    },
    {
      q: '¿Cuál es la política de cancelación de reservas?',
      a: 'Puedes cancelar tu reserva sin penalización hasta 7 días antes de la fecha de entrada con reembolso completo a tu cuenta. Para cancelaciones con menos de 7 días se aplica un cobro del 10%.'
    },
    {
      q: '¿Ofrecen servicio de transporte desde el Aeropuerto Rafael Núñez?',
      a: 'Sí, disponemos de servicio de traslado privado VIP en camioneta de lujo desde el aeropuerto hacia cualquiera de nuestras 4 sucursales.'
    },
    {
      q: '¿Qué formas de pago aceptan?',
      a: 'Aceptamos tarjetas de crédito y débito (Visa, Mastercard, American Express), transferencias bancarias, PSE y pagos con saldo a través de nuestra pasarela segura integrada.'
    }
  ];

  toggle(idx: number): void {
    this.openIdx = this.openIdx === idx ? null : idx;
  }
}

// frontend/src/components/FaqSection.jsx
import { useState } from 'react';

const FAQS = [
  {
    q: '¿Cuáles son los horarios de Check-in y Check-out?',
    a: 'El Check-in está disponible a partir de las 15:00 hrs y el Check-out se realiza hasta las 12:00 hrs del mediodía. Si necesitas check-in temprano o salida tardía, puedes solicitarlo previamente con nuestro equipo de Concierge.'
  },
  {
    q: '¿Cuál es la política de cancelación y reembolso?',
    a: 'Las reservas pueden cancelarse sin cargo directo desde tu panel de usuario. En caso de contar con un abono previo, el reembolso del importe pagado se realiza automáticamente a tu cuenta bancaria o método de pago en un plazo garantizado de 24 a 48 horas.'
  },
  {
    q: '¿Aceptan mascotas en las sucursales?',
    a: 'Aceptamos mascotas pequeñas (hasta 10 kg) en sucursales seleccionadas previa confirmación y disponibilidad de habitaciones dog-friendly equipadas con cama y tazón de bienvenida.'
  },
  {
    q: '¿Cuentan con servicio de transporte desde el aeropuerto?',
    a: 'Sí, ofrecemos servicio VIP de traslado en vehículo ejecutivo privado o camioneta de lujo desde el Aeropuerto Internacional Rafael Núñez directamente a la sucursal de tu elección.'
  },
  {
    q: '¿Qué formas de pago aceptan?',
    a: 'Aceptamos tarjetas de crédito y débito (Visa, Mastercard, American Express), transferencias bancarias, PSE y pagos con saldo a través de nuestra pasarela segura integrada.'
  }
];

export default function FaqSection() {
  const [openIdx, setOpenIdx] = useState(0);

  const toggle = (idx) => {
    setOpenIdx(openIdx === idx ? null : idx);
  };

  return (
    <section id="faq" style={{ padding: '4rem 1.5rem', backgroundColor: '#0d0d0d' }}>
      <div style={{ maxWidth: '900px', margin: '0 auto' }}>
        <div className="rooms-header" style={{ textAlign: 'center', marginBottom: '3rem' }}>
          <p className="sec-label">Preguntas frecuentes</p>
          <h2 className="sec-title">Resuelve tus dudas antes de viajar</h2>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {FAQS.map((faq, idx) => {
            const isOpen = openIdx === idx;
            return (
              <div
                key={idx}
                style={{
                  background: 'rgba(255, 255, 255, 0.02)',
                  border: '1px solid rgba(212, 175, 55, 0.2)',
                  borderRadius: '8px',
                  overflow: 'hidden'
                }}
              >
                <button
                  type="button"
                  onClick={() => toggle(idx)}
                  style={{
                    width: '100%',
                    padding: '1.25rem 1.5rem',
                    display: 'flex',
                    justify: 'space-between',
                    alignItems: 'center',
                    background: 'none',
                    border: 'none',
                    color: '#ffffff',
                    fontSize: '1.05rem',
                    fontWeight: 600,
                    cursor: 'pointer',
                    textAlign: 'left'
                  }}
                >
                  <span>{faq.q}</span>
                  <span style={{ color: 'var(--gold)', fontSize: '1.3rem', marginLeft: '1rem' }}>
                    {isOpen ? '−' : '+'}
                  </span>
                </button>
                {isOpen && (
                  <div
                    style={{
                      padding: '0 1.5rem 1.25rem 1.5rem',
                      color: '#cccccc',
                      lineHeight: 1.6,
                      borderTop: '1px solid rgba(255, 255, 255, 0.05)'
                    }}
                  >
                    <p style={{ margin: 0 }}>{faq.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
