// frontend-angular/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer>
      <div className="footer-top">
        <div className="footer-col">
          <p className="footer-logo">Palacio del Mar</p>
          <p className="footer-desc">
            Hotel boutique de lujo en el centro histórico amurallado de Cartagena de Indias.
          </p>
          <div className="footer-awards">
            <span className="footer-award">🏆 Travellers' Choice 2026</span>
            <span className="footer-award">⭐ 9.8 Booking.com</span>
          </div>
        </div>

        <div className="footer-col">
          <h4>Explorar</h4>
          <ul>
            <li (click)="scrollTo('#rooms')">Suites</li>
            <li (click)="scrollTo('#experiences')">Experiencias</li>
            <li (click)="scrollTo('#dining')">Gastronomía</li>
            <li (click)="scrollTo('#spa')">Spa</li>
            <li (click)="scrollTo('#faq')">Preguntas frecuentes</li>
          </ul>
        </div>

        <div className="footer-col">
          <h4>Contacto VIP</h4>
          <ul>
            <li><a href="mailto:reservas@palaciomar.co" style="color: inherit; text-decoration: none;">reservas&#64;palaciomar.co</a></li>
            <li><a href="https://wa.me/573009876543" target="_blank" rel="noreferrer" style="color: inherit; text-decoration: none;">+57 300 987 6543</a></li>
            <li>Calle del Santísimo # 8-12, Centro Histórico</li>
          </ul>
        </div>

        <div className="footer-col">
          <h4>Síguenos</h4>
          <div className="social-links">
            <a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram</a>
            <a href="https://facebook.com" target="_blank" rel="noreferrer">Facebook</a>
          </div>
        </div>
      </div>

      <div className="footer-bottom">
        <p>© {{ currentYear }} Palacio del Mar · Todos los derechos reservados.</p>
      </div>
    </footer>
  `
})
export class FooterComponent {
  currentYear = new Date().getFullYear();

  scrollTo(selector: string): void {
    document.querySelector(selector)?.scrollIntoView({ behavior: 'smooth' });
  }
}

// frontend/src/components/Footer.jsx
export default function Footer() {
  const year = new Date().getFullYear();
  return (
    <footer>
      <div className="footer-top">
        <div className="footer-col">
          <p className="footer-logo">Palacio del Mar</p>
          <p className="footer-desc">
            Hotel boutique de lujo en el centro histórico amurallado de Cartagena de Indias.
          </p>
          <div className="footer-awards">
            <span className="footer-award">🏆 Travellers' Choice 2026</span>
            <span className="footer-award">⭐ 9.8 Booking.com</span>
          </div>
        </div>
        <div className="footer-col">
          <strong>Explorar</strong>
          <a href="#rooms">Suites</a>
          <a href="#experiences">Experiencias</a>
          <a href="#dining">Gastronomía</a>
          <a href="#spa">Spa</a>
          <a href="#faq">Preguntas frecuentes</a>
        </div>
        <div className="footer-col">
          <strong>Contacto VIP</strong>
          <a href="mailto:reservas@palaciomar.co">reservas@palaciomar.co</a>
          <a href="https://wa.me/573009876543" target="_blank" rel="noreferrer">+57 300 987 6543</a>
          <span>Calle del Santísimo # 8-12, Centro Histórico, Cartagena</span>
        </div>
        <div className="footer-col">
          <strong>Síguenos</strong>
          <div className="social-links">
            <a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram</a>
            <a href="https://facebook.com" target="_blank" rel="noreferrer">Facebook</a>
          </div>
        </div>
      </div>
      <div className="footer-bottom">
        <span>© {year} Palacio del Mar · Todos los derechos reservados.</span>
      </div>
    </footer>
  );
}
