// frontend/src/components/RoomsSection.jsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '../api/client';
import { useBookingCart } from '../context/BookingCartContext.jsx';
import { formatCOP } from '../utils/format';

const shortBranch = (name = '') => name.replace(/^Palacio del Mar\s*·\s*/, '');

export default function RoomsSection() {
  const [suites, setSuites] = useState(null);
  const [error, setError] = useState(false);
  const [types, setTypes] = useState([]);
  const [typeFilter, setTypeFilter] = useState('');
  const [branches, setBranches] = useState([]);
  const [branch, setBranch] = useState(''); // '' = todas las sucursales
  const { availability, search, startBooking } = useBookingCart();

  const fetchSuites = useCallback(() => {
    setSuites(null);
    setError(false);
    api.get('/suites', {
      params: { limit: 50, sortBy: 'order', sortOrder: 'asc', ...(branch ? { branch } : {}) } })
      .then((res) => setSuites(res.data.data))
      .catch(() => {
        setSuites([]);
        setError(true);
      });
  }, [branch]);

  useEffect(() => {
    fetchSuites();
  }, [fetchSuites]);

  // Sucursales para las pestañas (GET /branches)
  useEffect(() => {
    api.get('/branches')
      .then((res) => setBranches(res.data.data || []))
      .catch(() => setBranches([]));
  }, []);

  // Tipos de suite para el filtro (GET /suites/types)
  useEffect(() => {
    api.get('/suites/types')
      .then((res) => setTypes(res.data.data || []))
      .catch(() => setTypes([]));
  }, []);

  // Si el huésped ya buscó disponibilidad (BookingBar), mostramos precio y
  // disponibilidad reales para esas fechas en vez del precio base genérico.
  const availabilityMap = useMemo(() => {
    if (!availability) return null;
    const map = new Map();
    availability.availableSuites.forEach((s) => map.set(s._id, { ...s, isAvailable: true }));
    (availability.unavailableSuites || []).forEach((s) => map.set(s._id, { ...s, isAvailable: false }));
    return map;
  }, [availability]);

  const visibleSuites = suites && typeFilter ? suites.filter((s) => s.type === typeFilter) : suites;

  const openBooking = (suite) => {
    startBooking(suite);
  };

  if (suites === null) {
    return (
      <section id="rooms">
        <div className="rooms-header">
          <p className="sec-label">Alojamiento</p>
          <h2 className="sec-title">Nuestras suites</h2>
        </div>
        <div className="rooms-grid"><div className="spinner" /></div>
      </section>
    );
  }

  if (suites.length === 0) {
    return (
      <section id="rooms">
        <div className="rooms-header">
          <p className="sec-label">Alojamiento</p>
          <h2 className="sec-title">Nuestras suites</h2>
        </div>
        <div style={{ textAlign: 'center', padding: '3rem 1rem' }}>
          <p className="form-hint" style={{ marginBottom: '1rem' }}>
            {error
              ? 'No pudimos conectar con el servidor. Intenta de nuevo en unos segundos.'
              : 'Todavía no hay habitaciones cargadas. Vuelve pronto.'}
          </p>
          <button className="btn-outline" onClick={fetchSuites}>Reintentar</button>
        </div>
      </section>
    );
  }

  return (
    <section id="rooms">
      <div className="rooms-header">
        <p className="sec-label">Alojamiento</p>
        <h2 className="sec-title">Nuestras suites</h2>
        <p className="sec-sub">
          {availability
            ? `Disponibilidad para ${availability.nights} noche(s), del ${new Date(availability.checkIn).toLocaleDateString('es-CO')} al ${new Date(availability.checkOut).toLocaleDateString('es-CO')}`
            : 'Elige tu zona en Cartagena: murallas coloniales, Getsemaní, Bocagrande o La Boquilla'}
        </p>
      </div>
      {branches.length > 1 && (
        <div className="filter-row" role="group" aria-label="Elegir sucursal">
          <button type="button" className={`filter-btn ${branch === '' ? 'is-active' : ''}`} onClick={() => setBranch('')}>
            Todas las sucursales
          </button>
          {branches.map((b) => (
            <button
              type="button"
              key={b.slug}
              className={`filter-btn ${branch === b.slug ? 'is-active' : ''}`}
              title={b.fromPrice ? `Desde ${formatCOP(b.fromPrice)} por noche` : undefined}
              onClick={() => { setBranch(b.slug); setTypeFilter(''); }}
            >
              {shortBranch(b.name)}{b.roomTypes ? ` (${b.roomTypes})` : ''}
            </button>
          ))}
        </div>
      )}
      {types.length > 1 && (
        <div className="filter-row" role="group" aria-label="Filtrar por tipo de suite">
          <button type="button" className={`filter-btn ${typeFilter === '' ? 'is-active' : ''}`} onClick={() => setTypeFilter('')}>
            Todas
          </button>
          {types.map((t) => (
            <button
              type="button"
              key={t.name}
              className={`filter-btn ${typeFilter === t.name ? 'is-active' : ''}`}
              title={t.minPrice ? `Desde ${formatCOP(t.minPrice)} por noche` : undefined}
              onClick={() => setTypeFilter(t.name)}
            >
              {t.name} ({t.count})
            </button>
          ))}
        </div>
      )}
      <div className="rooms-grid">
        {visibleSuites.map((suite) => {
          const av = availabilityMap?.get(suite._id);
          const isUnavailable = av && !av.isAvailable;
          const nightly = av?.pricePerNight ?? suite.seasonalPrice ?? suite.basePrice;
          const totalForStay = av?.totalPrice;

          return (
            <div className={`room-card ${isUnavailable ? 'room-unavailable' : ''}`} key={suite._id}>
              <div className="room-img-wrap">
                <img src={suite.mainImage} alt={suite.name} loading="lazy" />
                {suite.featured && <span className="room-avail badge-ok">Recomendada</span>}
                {isUnavailable && <span className="room-avail badge-few">No disponible</span>}
              </div>
              <div className="room-info">
                <p className="room-type">{suite.type}{suite.branch?.name ? ` · ${shortBranch(suite.branch.name)}` : ''}</p>
                <h3 className="room-name">{suite.name}</h3>
                <div className="room-chips">
                  {(suite.amenities || []).slice(0, 3).map((a) => (
                    <span className="chip" key={a}>{a}</span>
                  ))}
                  <span className="chip">{suite.size} m²</span>
                  <span className="chip">Hasta {suite.maxGuests} huéspedes</span>
                </div>
                <div className="room-price">
                  {suite.originalPrice > suite.basePrice && (
                    <span className="price-old">{formatCOP(suite.originalPrice)}</span>
                  )}
                  <strong>{formatCOP(nightly)}</strong>
                  <span> / noche</span>
                </div>
                {totalForStay && (
                  <p className="form-hint">Total por {availability.nights} noches: {formatCOP(totalForStay)}</p>
                )}
                <button
                  className="btn-book room-cta"
                  disabled={isUnavailable}
                  onClick={() => openBooking(suite)}
                >
                  {isUnavailable ? 'No disponible' : 'Reservar'}
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}

// frontend-angular/src/app/components/rooms-section/rooms-section.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Suite, Branch } from '../../models/types';
import { BookingModalComponent } from '../booking-modal/booking-modal.component';

@Component({
  selector: 'app-rooms-section',
  standalone: true,
  imports: [CommonModule, RouterModule, BookingModalComponent],
  template: `
    <section id="rooms">
      <div class="rooms-header">
        <p class="sec-label">Alojamiento</p>
        <h2 class="sec-title">Nuestras suites</h2>
        <p class="sec-sub">
          Elige tu zona en Cartagena: murallas coloniales, Getsemaní, Bocagrande o La Boquilla
        </p>
      </div>

      <!-- Sucursales Filter -->
      <div class="filter-row" *ngIf="branches.length > 0">
        <button
          type="button"
          class="filter-btn"
          [class.is-active]="selectedBranch === ''"
          (click)="selectBranch('')"
        >
          Todas las sucursales
        </button>
        <button
          *ngFor="let b of branches"
          type="button"
          class="filter-btn"
          [class.is-active]="selectedBranch === b.slug"
          (click)="selectBranch(b.slug)"
        >
          {{ getShortBranch(b.name) }}
        </button>
      </div>

      <!-- Tipos Filter -->
      <div class="filter-row" *ngIf="types.length > 0" style="margin-top: 10px;">
        <button
          type="button"
          class="filter-btn"
          [class.is-active]="selectedType === ''"
          (click)="selectedType = ''"
        >
          Todas
        </button>
        <button
          *ngFor="let t of types"
          type="button"
          class="filter-btn"
          [class.is-active]="selectedType === t.name"
          (click)="selectedType = t.name"
        >
          {{ t.name }} ({{ t.count }})
        </button>
      </div>

      <!-- Loading / Empty states -->
      <div *ngIf="loading" style="text-align: center; padding: 4rem;">
        <p style="color: #c9a96e;">Cargando suites exclusivas…</p>
      </div>

      <div *ngIf="!loading && visibleSuites.length === 0" style="text-align: center; padding: 4rem;">
        <p style="color: rgba(245, 240, 232, 0.6);">No hay suites disponibles para los filtros seleccionados.</p>
      </div>

      <!-- Rooms Grid -->
      <div class="rooms-grid" *ngIf="!loading && visibleSuites.length > 0">
        <div class="room-card" *ngFor="let suite of visibleSuites">
          <div class="room-img-wrap">
            <img [src]="suite.mainImage || 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'" [alt]="suite.name" loading="lazy" />
            <span class="room-avail badge-ok" *ngIf="suite.featured">Recomendada</span>
          </div>

          <div class="room-info">
            <p class="room-type">
              {{ suite.type || 'Suite' }}
              <span *ngIf="suite.branch?.name"> · {{ getShortBranch(suite.branch?.name || '') }}</span>
            </p>

            <h3 class="room-name">
              <a [routerLink]="['/habitaciones', suite.slug || suite.id || suite._id]">
                {{ suite.name }}
              </a>
            </h3>

            <div class="room-chips">
              <span class="chip" *ngFor="let amenity of (suite.amenities || []).slice(0, 3)">
                {{ amenity }}
              </span>
              <span class="chip">{{ suite.size || 35 }} m²</span>
              <span class="chip">Hasta {{ suite.maxGuests || 2 }} huéspedes</span>
            </div>

            <div class="room-price">
              <span class="price-old" *ngIf="suite.originalPrice">$ {{ suite.originalPrice | number:'1.0-0' }}</span>
              <strong>$ {{ (suite.basePrice || suite.pricePerNight || 450000) | number:'1.0-0' }}</strong>
              <span> / noche</span>
            </div>

            <a class="room-detail-link" [routerLink]="['/habitaciones', suite.slug || suite.id || suite._id]">
              Ver detalles
            </a>

            <button class="btn-book room-cta" (click)="openBookingModal(suite)">
              Reservar
            </button>
          </div>
        </div>
      </div>
    </section>

    <app-booking-modal [isOpen]="bookingModalOpen" [suite]="selectedSuiteForBooking" (closeEvent)="bookingModalOpen = false"></app-booking-modal>
  `
})
export class RoomsSectionComponent implements OnInit {
  suites: Suite[] = [];
  branches: Branch[] = [];
  types: any[] = [];
  selectedBranch: string = '';
  selectedType: string = '';
  loading = true;

  bookingModalOpen = false;
  selectedSuiteForBooking: Suite | null = null;

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.fetchData();
  }

  fetchData(): void {
    this.api.get<any>('/branches').subscribe({
      next: (res) => {
        this.branches = res.data || res;
      }
    });

    this.api.get<any>('/suites/types').subscribe({
      next: (res) => {
        this.types = res.data || res;
      }
    });

    this.api.get<any>('/suites').subscribe({
      next: (res) => {
        this.suites = res.data || res;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  selectBranch(slug: string): void {
    this.selectedBranch = slug;
  }

  get visibleSuites(): Suite[] {
    return this.suites.filter(s => {
      if (this.selectedBranch) {
        const bSlug = s.branch?.slug || '';
        if (bSlug !== this.selectedBranch) return false;
      }
      if (this.selectedType) {
        if (s.type !== this.selectedType) return false;
      }
      return true;
    });
  }

  getShortBranch(name: string): string {
    return name.replace(/^Palacio del Mar\s*·\s*/i, '');
  }

  openBookingModal(suite: Suite): void {
    this.selectedSuiteForBooking = suite;
    this.bookingModalOpen = true;
  }
}
